language: cpp 
dist: trusty 
sudo: required 
matrix:
 include: 
  - compiler: gcc 
    env: PACKAGE='CHECK' 
  - compiler: clang-3.6
    env: PACKAGE='CHECK' 
  - compiler: clang-3.6
    env: PACKAGE='AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations ' 
  - compiler: clang-3.6
    env: PACKAGE='Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres ' 
  - compiler: clang-3.6
    env: PACKAGE='Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Arithmetic_kernel Arrangement_on_surface_2 Barycentric_coordinates_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='BGL Boolean_set_operations_2 Bounding_volumes ' 
  - compiler: clang-3.6
    env: PACKAGE='Box_intersection_d Cartesian_kernel CGAL_Core ' 
  - compiler: clang-3.6
    env: PACKAGE='CGAL_ImageIO CGAL_ipelets Circular_kernel_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Circular_kernel_3 Circulator Classification ' 
  - compiler: clang-3.6
    env: PACKAGE='Combinatorial_map Cone_spanners_2 Convex_decomposition_3 ' 
  - compiler: clang-3.6
    env: PACKAGE='Convex_hull_2 Convex_hull_3 Convex_hull_d ' 
  - compiler: clang-3.6
    env: PACKAGE='Distance_2 Distance_3 Envelope_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Envelope_3 Filtered_kernel Generalized_map ' 
  - compiler: clang-3.6
    env: PACKAGE='Generator Geomview GraphicsView ' 
  - compiler: clang-3.6
    env: PACKAGE='HalfedgeDS Hash_map Homogeneous_kernel ' 
  - compiler: clang-3.6
    env: PACKAGE='Inscribed_areas Installation Interpolation ' 
  - compiler: clang-3.6
    env: PACKAGE='Intersections_2 Intersections_3 Interval_skip_list ' 
  - compiler: clang-3.6
    env: PACKAGE='Interval_support Inventor Jet_fitting_3 ' 
  - compiler: clang-3.6
    env: PACKAGE='Kernel_23 Kernel_d LEDA ' 
  - compiler: clang-3.6
    env: PACKAGE='Linear_cell_complex MacOSX Maintenance ' 
  - compiler: clang-3.6
    env: PACKAGE='Matrix_search Mesh_2 Mesh_3 ' 
  - compiler: clang-3.6
    env: PACKAGE='Mesher_level Minkowski_sum_2 Minkowski_sum_3 ' 
  - compiler: clang-3.6
    env: PACKAGE='Modifier Modular_arithmetic Nef_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Nef_3 Nef_S2 NewKernel_d ' 
  - compiler: clang-3.6
    env: PACKAGE='Number_types OpenNL Operations_on_polyhedra ' 
  - compiler: clang-3.6
    env: PACKAGE='Optimal_transportation_reconstruction_2 Optimisation_basic Partition_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Periodic_2_triangulation_2 Periodic_3_mesh_3 Periodic_3_triangulation_3 ' 
  - compiler: clang-3.6
    env: PACKAGE='Point_set_2 Point_set_3 Point_set_processing_3 ' 
  - compiler: clang-3.6
    env: PACKAGE='Point_set_shape_detection_3 Poisson_surface_reconstruction_3 Polygon ' 
  - compiler: clang-3.6
    env: PACKAGE='Polygon_mesh_processing Polyhedron Polyhedron_IO ' 
  - compiler: clang-3.6
    env: PACKAGE='Polyline_simplification_2 Polynomial Polytope_distance_d ' 
  - compiler: clang-3.6
    env: PACKAGE='Principal_component_analysis Principal_component_analysis_LGPL Profiling_tools ' 
  - compiler: clang-3.6
    env: PACKAGE='Property_map QP_solver Random_numbers ' 
  - compiler: clang-3.6
    env: PACKAGE='Ridges_3 Scale_space_reconstruction_3 Scripts ' 
  - compiler: clang-3.6
    env: PACKAGE='SearchStructures Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Set_movable_separability_2 Skin_surface_3 Snap_rounding_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Solver_interface Spatial_searching Spatial_sorting ' 
  - compiler: clang-3.6
    env: PACKAGE='STL_Extension Straight_skeleton_2 Stream_lines_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='Stream_support Subdivision_method_3 Surface_mesh ' 
  - compiler: clang-3.6
    env: PACKAGE='Surface_mesh_deformation Surface_mesher Surface_mesh_parameterization ' 
  - compiler: clang-3.6
    env: PACKAGE='Surface_mesh_segmentation Surface_mesh_shortest_path Surface_mesh_simplification ' 
  - compiler: clang-3.6
    env: PACKAGE='Surface_mesh_skeletonization Surface_sweep_2 TDS_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='TDS_3 Testsuite Three ' 
  - compiler: clang-3.6
    env: PACKAGE='Triangulation Triangulation_2 Triangulation_3 ' 
  - compiler: clang-3.6
    env: PACKAGE='Union_find Visibility_2 Voronoi_diagram_2 ' 
  - compiler: clang-3.6
    env: PACKAGE='wininst ' 
  - compiler: clang-3.6
    env: PACKAGE='Polyhedron_demo' 
install: 
  - bash .travis/install.sh 
  - if [[ "$CXX" = "clang++" ]]; then export CXX=clang++-3.6 CC=clang-3.6; fi
before_script: 
- wget -O doxygen_exe https://cgal.geometryfactory.com/~mgimeno/doxygen_exe
- sudo mv doxygen_exe /usr/bin/doxygen
- sudo chmod +x /usr/bin/doxygen
- mkdir -p build 
- cd build 
- cmake -DCMAKE_CXX_FLAGS="-std=c++11" -DCGAL_HEADER_ONLY=ON -DQt5_DIR="/opt/qt55/lib/cmake/Qt5" -DQt5Svg_DIR="/opt/qt55/lib/cmake/Qt5Svg" -DQt5OpenGL_DIR="/opt/qt55/lib/cmake/Qt5OpenGL" -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG .. 
- make 
- sudo make install &>/dev/null
- cd ..
- sudo bash ./.travis/install_openmesh.sh
script: 
- cd ./.travis
- bash -x -e ./build_package.sh $PACKAGE
notifications:
  email:
    on_success: change # default: always
    on_failure: always # default: always
